---
server:
  port: 8888

spring:
  security:
    user:
      name: testu
      password: testp
  cloud:
    config:
      server:
        git:
          uri: https://github.com/git-josip/config-server-repo
          search-paths: ['api', 'data-ingestion']
